# Generated by Django 6.0.7 on 2026-07-08 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_subscription_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=32)),
                ('event_id', models.CharField(max_length=128)),
                ('event_type', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=24)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'status'], name='billing_bil_provide_bbe373_idx'), models.Index(fields=['provider', 'processed_at'], name='billing_bil_provide_199ef2_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='uniq_provider_event_id')],
            },
        ),
    ]
