# Generated by Django 6.0.7 on 2026-07-09 11:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_workspace_onboarding_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('party_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('karigar', 'Karigar'), ('other', 'Other')], max_length=24)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('contacts', models.JSONField(blank=True, default=list)),
                ('addresses', models.JSONField(blank=True, default=list)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['workspace', 'party_type'], name='party_party_workspa_9b8e3f_idx'), models.Index(fields=['workspace', 'name'], name='party_party_workspa_0d3cfc_idx'), models.Index(fields=['workspace', 'is_active'], name='party_party_workspa_bc3c83_idx')],
            },
        ),
    ]
