# Generated by Django 6.0.7 on 2026-07-12 08:00

import django.db.models.deletion
import party.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_rls_policies'),
        ('workspaces', '0002_workspace_onboarding_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('registered', 'Registered'), ('billing', 'Billing'), ('shipping', 'Shipping'), ('home', 'Home'), ('work', 'Work'), ('kyc', 'KYC'), ('other', 'Other')], max_length=16)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('area', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(blank=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=24)),
                ('country', models.CharField(default='IN', max_length=2)),
                ('is_default', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['party', 'address_type', '-is_default', 'city'],
            },
        ),
        migrations.CreateModel(
            name='PartyCodeSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default='PARTY', max_length=32)),
                ('next_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PartyContactMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('mobile', 'Mobile'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('website', 'Website'), ('other', 'Other')], max_length=16)),
                ('label', models.CharField(blank=True, max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['party', 'contact_type', '-is_primary', 'value'],
            },
        ),
        migrations.CreateModel(
            name='PartyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('kyc', 'KYC'), ('tax', 'Tax'), ('contract', 'Contract'), ('license', 'License'), ('other', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to=party.models.party_document_upload_path)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['party', 'document_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PartyIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier_type', models.CharField(choices=[('pan', 'PAN'), ('aadhaar', 'Aadhaar'), ('gstin', 'GSTIN'), ('cin', 'CIN'), ('udyam', 'UDYAM'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('other', 'Other')], max_length=32)),
                ('value', models.CharField(max_length=128)),
                ('masked_value', models.CharField(blank=True, max_length=128)),
                ('value_hash', models.CharField(blank=True, max_length=128)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['party', 'identifier_type'],
            },
        ),
        migrations.CreateModel(
            name='PartyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('contact_person', 'Contact Person'), ('employer', 'Employer'), ('employee', 'Employee'), ('broker', 'Broker'), ('agent', 'Agent'), ('related_business', 'Related Business'), ('family', 'Family'), ('other', 'Other')], max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['from_party', 'relationship_type', 'to_party'],
            },
        ),
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('ended', 'Ended')], default='active', max_length=16)),
                ('segment', models.CharField(blank=True, max_length=64)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['party', 'role_type'],
            },
        ),
        migrations.CreateModel(
            name='PartyRoleType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AlterModelOptions(
            name='party',
            options={'ordering': ['display_name', 'name']},
        ),
        migrations.AddField(
            model_name='party',
            name='credit_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='party',
            name='gstin',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='party',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='party',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='party',
            name='normalized_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='party',
            name='party_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='party',
            name='primary_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='party',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='party',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='party_profiles/'),
        ),
        migrations.AddField(
            model_name='party',
            name='relation_label',
            field=models.CharField(blank=True, choices=[('son_of', 'Son Of'), ('daughter_of', 'Daughter Of'), ('care_of', 'Care Of'), ('parent_of', 'Parent Of'), ('father_of', 'Father Of'), ('wife_of', 'Wife Of'), ('husband_of', 'Husband Of'), ('other', 'Other')], max_length=16),
        ),
        migrations.AddField(
            model_name='party',
            name='relation_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='party',
            name='risk_level',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='party',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked'), ('archived', 'Archived')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='party',
            name='tax_pan',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='party',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('organization', 'Organization'), ('bank', 'Bank'), ('government', 'Government'), ('internal_workspace', 'Internal Workspace'), ('other', 'Other'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('karigar', 'Karigar')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['workspace', 'party_code'], name='party_party_workspa_145b27_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['workspace', 'display_name'], name='party_party_workspa_c6cb2c_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['workspace', 'normalized_name'], name='party_party_workspa_9033fa_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['workspace', 'tax_pan'], name='party_party_workspa_16a8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['workspace', 'gstin'], name='party_party_workspa_59625d_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['workspace', 'status', 'party_type'], name='party_party_workspa_1f32e8_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['workspace', 'credit_hold'], name='party_party_workspa_37cd0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('workspace', 'party_code'), name='party_workspace_code_uniq'),
        ),
        migrations.AddField(
            model_name='partyaddress',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partyaddress',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_addresses', to='party.party'),
        ),
        migrations.AddField(
            model_name='partyaddress',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='partycodesequence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partycodesequence',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='partycontactmethod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partycontactmethod',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_methods', to='party.party'),
        ),
        migrations.AddField(
            model_name='partycontactmethod',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='partydocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partydocument',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_documents', to='party.party'),
        ),
        migrations.AddField(
            model_name='partydocument',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='partyidentifier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partyidentifier',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_identifiers', to='party.party'),
        ),
        migrations.AddField(
            model_name='partyidentifier',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='partydocument',
            name='identifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_documents', to='party.partyidentifier'),
        ),
        migrations.AddField(
            model_name='partyrelationship',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partyrelationship',
            name='from_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='party.party'),
        ),
        migrations.AddField(
            model_name='partyrelationship',
            name='to_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='party.party'),
        ),
        migrations.AddField(
            model_name='partyrelationship',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='partyrole',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partyrole',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_roles', to='party.party'),
        ),
        migrations.AddField(
            model_name='partyrole',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='partyrole',
            name='role_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='party_roles', to='party.partyroletype'),
        ),
        migrations.AddIndex(
            model_name='partyaddress',
            index=models.Index(fields=['workspace', 'party', 'address_type'], name='party_party_workspa_2b0dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='partyaddress',
            index=models.Index(fields=['workspace', 'city', 'state'], name='party_party_workspa_4f1307_idx'),
        ),
        migrations.AddConstraint(
            model_name='partyaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('workspace', 'party', 'address_type'), name='party_address_one_default_per_type'),
        ),
        migrations.AddConstraint(
            model_name='partycodesequence',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='party_sequence_workspace_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='partycontactmethod',
            index=models.Index(fields=['workspace', 'party', 'contact_type'], name='party_party_workspa_0709a4_idx'),
        ),
        migrations.AddIndex(
            model_name='partycontactmethod',
            index=models.Index(fields=['workspace', 'normalized_value'], name='party_party_workspa_500489_idx'),
        ),
        migrations.AddConstraint(
            model_name='partycontactmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('workspace', 'party', 'contact_type'), name='party_contact_one_primary_per_type'),
        ),
        migrations.AddIndex(
            model_name='partyidentifier',
            index=models.Index(fields=['workspace', 'identifier_type', 'value_hash'], name='party_party_workspa_e6e796_idx'),
        ),
        migrations.AddIndex(
            model_name='partyidentifier',
            index=models.Index(fields=['workspace', 'party', 'identifier_type'], name='party_party_workspa_ffb0ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='partyidentifier',
            constraint=models.UniqueConstraint(fields=('workspace', 'party', 'identifier_type'), name='party_identifier_one_per_type'),
        ),
        migrations.AddIndex(
            model_name='partydocument',
            index=models.Index(fields=['workspace', 'party', 'document_type'], name='party_party_workspa_743a10_idx'),
        ),
        migrations.AddIndex(
            model_name='partydocument',
            index=models.Index(fields=['workspace', 'expires_on'], name='party_party_workspa_350ec0_idx'),
        ),
        migrations.AddIndex(
            model_name='partyrelationship',
            index=models.Index(fields=['workspace', 'from_party', 'relationship_type'], name='party_party_workspa_2afddb_idx'),
        ),
        migrations.AddIndex(
            model_name='partyrelationship',
            index=models.Index(fields=['workspace', 'to_party', 'relationship_type'], name='party_party_workspa_8e184f_idx'),
        ),
        migrations.AddConstraint(
            model_name='partyrelationship',
            constraint=models.UniqueConstraint(fields=('workspace', 'from_party', 'to_party', 'relationship_type'), name='party_relationship_unique_type'),
        ),
        migrations.AddConstraint(
            model_name='partyrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('from_party', models.F('to_party')), _negated=True), name='party_relationship_not_self'),
        ),
        migrations.AddIndex(
            model_name='partyrole',
            index=models.Index(fields=['workspace', 'party', 'status'], name='party_party_workspa_575cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='partyrole',
            index=models.Index(fields=['workspace', 'role_type', 'status'], name='party_party_workspa_49a2a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='partyrole',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('workspace', 'party', 'role_type'), name='party_role_one_active_per_type'),
        ),
    ]
