"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


def _load_dotenv(path: Path) -> None:
    if not path.exists():
        return

    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


_load_dotenv(BASE_DIR / '.env')


def _load_json_env(name: str, default: str = '{}'):
    try:
        return json.loads(os.getenv(name, default))
    except json.JSONDecodeError:
        return json.loads(default)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-yixia+#vsd_kg$vy1+pe3m^8wzcuc8bo798&wvon06@x!dr%v3')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'false').lower() == 'true'

ALLOWED_HOSTS = [h for h in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if h]


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
]

THIRD_PARTY_APPS = [
    'allauth',
    'allauth.account',
]

LOCAL_APPS = [
    'core',
    'common',
    'accounts',
    'workspaces',
    'memberships',
    'workspace_invitations',
    'authorization',
    'billing',
    'notes',
    'platform_admin',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.middleware.RequestRateLimitMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'core.middleware.WorkspaceContextMiddleware',
    'core.middleware.RLSContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.navigation',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').lower()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3'
        if DB_ENGINE == 'sqlite'
        else 'django.db.backends.postgresql',
        'NAME': str(BASE_DIR / 'db.sqlite3')
        if DB_ENGINE == 'sqlite'
        else os.getenv('DB_NAME', 'rls_rokkad'),
        'USER': '' if DB_ENGINE == 'sqlite' else os.getenv('DB_USER', 'postgres'),
        'PASSWORD': '' if DB_ENGINE == 'sqlite' else os.getenv('DB_PASSWORD', 'postgres'),
        'HOST': '' if DB_ENGINE == 'sqlite' else os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': '' if DB_ENGINE == 'sqlite' else os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Transaction-local PostgreSQL setting name used by RLS policies.
RLS_WORKSPACE_SETTING = 'app.current_workspace_id'
# Keep False by default under Django autocommit; set True only when request/service flows run in explicit transactions.
RLS_CONTEXT_LOCAL = os.getenv('RLS_CONTEXT_LOCAL', 'false').lower() == 'true'

SITE_ID = int(os.getenv('SITE_ID', '1'))

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

ACCOUNT_EMAIL_VERIFICATION = os.getenv('ACCOUNT_EMAIL_VERIFICATION', 'mandatory')
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# Security headers and cookie hardening
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.getenv('SECURE_REFERRER_POLICY', 'strict-origin-when-cross-origin')
SECURE_CROSS_ORIGIN_OPENER_POLICY = os.getenv('SECURE_CROSS_ORIGIN_OPENER_POLICY', 'same-origin')
X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'DENY')

SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'false').lower() == 'true'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'false').lower() == 'true'

SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'false').lower() == 'true'
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'false').lower() == 'true'
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'false').lower() == 'true'

# Basic app-layer rate limiting
RATE_LIMIT_ENABLED = os.getenv('RATE_LIMIT_ENABLED', 'true').lower() == 'true'
RATE_LIMIT_WINDOW_SECONDS = int(os.getenv('RATE_LIMIT_WINDOW_SECONDS', '60'))
RATE_LIMIT_LOGIN_MAX_REQUESTS = int(os.getenv('RATE_LIMIT_LOGIN_MAX_REQUESTS', '20'))
RATE_LIMIT_WRITE_MAX_REQUESTS = int(os.getenv('RATE_LIMIT_WRITE_MAX_REQUESTS', '120'))

# Billing provider integration settings
BILLING_PROVIDER = os.getenv('BILLING_PROVIDER', 'mock')
BILLING_USE_SDK = os.getenv('BILLING_USE_SDK', 'false').lower() == 'true'

# Stripe billing configuration
BILLING_STRIPE_SECRET_KEY = os.getenv('BILLING_STRIPE_SECRET_KEY', '')
BILLING_STRIPE_PRICE_LOOKUP = _load_json_env('BILLING_STRIPE_PRICE_LOOKUP')

# Razorpay billing configuration
BILLING_RAZORPAY_KEY_ID = os.getenv('BILLING_RAZORPAY_KEY_ID', '')
BILLING_RAZORPAY_KEY_SECRET = os.getenv('BILLING_RAZORPAY_KEY_SECRET', '')
BILLING_RAZORPAY_PLAN_LOOKUP = _load_json_env('BILLING_RAZORPAY_PLAN_LOOKUP')

# Webhook secrets (global fallback + provider-specific)
BILLING_WEBHOOK_SECRET = os.getenv('BILLING_WEBHOOK_SECRET', '')
BILLING_WEBHOOK_SECRET_STRIPE = os.getenv('BILLING_WEBHOOK_SECRET_STRIPE', '')
BILLING_WEBHOOK_SECRET_RAZORPAY = os.getenv('BILLING_WEBHOOK_SECRET_RAZORPAY', '')
